[package]
name = "rusty_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"

strum = "0.24"
strum_macros = "0.24"

hidapi = "1.3.3"

palette = "0.6"

tokio = { version = "1.17.0", features = ["full"] }

actix-web = "4"
actix-web-lab = "0.10"
actix-cors = "0.6.0"
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
juniper = "0.15.9"
