version: "3"

name: grafana

networks:
  loki:

services:
  loki:
    # This version is used because the newer ones break on ARM
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    volumes:
      - loki-data:/loki
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.7.4
    command: -config.file=/mnt/config/config.yml
    volumes:
      - ./config/promtail.yaml:/mnt/config/config.yaml
      - /var/log/rusty-controller:/var/log/rusty-controller
    networks:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loki
    restart: unless-stopped

volumes:
  grafana-data:
  loki-data:
